FROM debian:trixie-slim AS build

ENV TOX_VERSION=v0.2.21

RUN mkdir -p /build
COPY build /build/
RUN chmod +x /build/*.sh
RUN apt update && apt-get install -y libsodium-dev libvpx-dev libopus-dev cmake autoconf libtool automake gcc g++ libconfig-dev make file linux-headers-$(/build/linux-headers.sh) git
RUN mkdir -p /build && \
 cd /build && \
 git clone https://github.com/TokTok/c-toxcore --recursive -b ${TOX_VERSION} c-toxcore && \
 cd c-toxcore && \
 autoreconf -vif && ./configure --enable-static=true --disable-shared --enable-daemon --enable-dht-bootstrap && \
 make -j2

FROM debian:trixie-slim
RUN apt update && apt-get install -y libsodium23 libconfig11 bash python3-jinja2 python3-requests
RUN mkdir -p /opt/tox /var/lib/tox-bootstrapd /etc

COPY --from=build /build/c-toxcore/build/tox-bootstrapd /opt/tox/
COPY --from=build /build/c-toxcore/other/bootstrap_daemon/tox-bootstrapd.conf /opt/tox/tox-bootstrapd.conf

ENV NODES_URL=https://nodes.tox.chat/json \
  PORT=33445 \
  KEYS_FILE_PATH='/var/lib/tox-bootstrapd/keys' \
  PID_FILE_PATH='/var/run/tox-bootstrapd/tox-bootstrapd.pid' \
  ENABLE_IPV6=true \
  ENABLE_IPV4_FALLBACK=true \
  ENABLE_LAN_DISCOVERY=false \
  ENABLE_TCP_RELAY=true \
  TCP_RELAY_PORTS="[3389,33445]" \
  ENABLE_MOTD=true \
  MOTD=tox-bootstrapd

ADD entrypoint.sh /entrypoint.sh
ADD tox-bootstrapd.conf.j2 /opt/tox/tox-bootstrapd.conf.j2
ADD render.py /opt/tox/render.py
RUN chmod +x /entrypoint.sh /opt/tox/render.py

EXPOSE 3389/tcp
EXPOSE 33445/tcp
EXPOSE 33445/udp

ENTRYPOINT ["/entrypoint.sh"]
